export const ENGLISH_DEMO_ENABLED = true;

export const ENGLISH_LESSON_RUNTIME_META = {
  L1: { labN: "Sound Waves Lab" },
  L2: { labN: "Harmonics Lab" },
  L3: { labN: "Piano Roll Lab" },
  L4: { labN: "Song Maker" },
  L5: { labN: "Melody Maker" },
  L6: { labN: "Arpeggios Lab" },
  L7: { labN: "Strings Lab" },
  L8: { labN: "Shared Piano" },
  L9: { labN: "Rhythm Lab" },
  L10: { labN: "Song Maker" },
  L11: { labN: "Rhythm Lab" },
  L12: { labN: "Song Maker" },
};

export const ENGLISH_PPT_LESSON_DATA = {
  L1: {
    lessonId: "L1",
    lessonNumber: 1,
    chapterId: "ch1",
    chapter: "Chapter 1 - Musical Sound System",
    lessonTitle: "Properties of Sound and the Musical Sound System",
    knowledgePoints: [
      { title: "Four Properties of Sound", detail: "Pitch, duration, loudness, and timbre as physical and musical properties." },
      { title: "Musical Sound and Noise", detail: "Understand regular vibration and its relationship to musical tone." },
      { title: "Scale Degrees", detail: "Recognize the seven basic pitch names C, D, E, F, G, A, and B." },
      { title: "Altered Degrees", detail: "Understand how sharps, flats, and naturals change pitch." },
      { title: "Whole Steps and Half Steps", detail: "Understand the smallest distance unit and the natural half steps E-F and B-C." },
      { title: "Enharmonic Equivalence", detail: "Build the idea that different spellings can represent the same sounding pitch." },
    ],
    keyPoints: [
      "The four physical properties of sound and their causes.",
      "The seven basic pitch names and solfege equivalents.",
      "How to distinguish whole steps and half steps.",
      "Natural half-step locations on the keyboard.",
    ],
    difficultPoints: [
      "Understanding timbre as a result of the harmonic spectrum.",
      "Identifying whole and half steps on both keyboard and staff.",
      "Separating basic pitch names from altered pitch names.",
    ],
    inClassExercises: [
      "Classify piano sound, drum sound, wind noise, and flute sound as musical tone or noise.",
      "Mark all natural half steps in the C major scale.",
      "Write the pitch a half step above C and a half step below G.",
      "Explain how listeners distinguish two performers playing A4 at the same loudness on the same piano.",
    ],
    homework: [
      "Concept chart: summarize pitch, duration, loudness, and timbre with one real-life example for each.",
      "Rule application: mark basic degrees, altered degrees, natural half steps, and whole steps on a keyboard or pitch sequence.",
      "Short analysis: compare the timbre of two instruments playing the same pitch and explain the reason.",
    ],
  },
  L2: {
    lessonId: "L2",
    lessonNumber: 2,
    chapterId: "ch1",
    chapter: "Chapter 1 - Musical Sound System",
    lessonTitle: "Registers, Temperament, Enharmonic Equivalence, and Harmonics",
    knowledgePoints: [
      { title: "Register Grouping", detail: "Understand the complete system from low registers to high registers." },
      { title: "Middle C", detail: "Locate middle C as C4, about 261.63 Hz." },
      { title: "Equal Temperament", detail: "Understand the modern keyboard standard and the twelfth-root-of-two semitone ratio." },
      { title: "Just and Pythagorean Tuning", detail: "Compare natural harmonic ratios with fifth-based pitch generation." },
      { title: "Enharmonic Equivalence", detail: "Understand pitch names that sound the same but are spelled differently." },
      { title: "Harmonic Series", detail: "Connect harmonics with timbre and the basis of harmony." },
    ],
    keyPoints: [
      "Register grouping and middle C on the piano.",
      "Basic comparison of equal temperament, just intonation, and Pythagorean tuning.",
      "The physical relationship between harmonics and timbre.",
      "The difference between range and register.",
    ],
    difficultPoints: [
      "Understanding the strengths and limits of different tuning systems.",
      "Connecting the harmonic series to Western harmony.",
      "Choosing enharmonic spelling in tonal contexts.",
    ],
    inClassExercises: [
      "Identify the register group of c1, a2, F, c4, and E1.",
      "Write enharmonic spellings for F-sharp, E-flat, A-sharp, and D-flat.",
      "If the fundamental is 110 Hz, write the first six harmonic frequencies.",
      "Compare equal temperament and just intonation.",
    ],
    homework: [
      "Concept chart: create a register, middle C, and common range table.",
      "Rule application: explain equal temperament, just intonation, and Pythagorean tuning in one sentence each.",
      "Short analysis: use the harmonic series to explain why instruments differ in timbre.",
    ],
  },
  L3: {
    lessonId: "L3",
    lessonNumber: 3,
    chapterId: "ch2",
    chapter: "Chapter 2 - Notation",
    lessonTitle: "Clefs and Staves",
    knowledgePoints: [
      { title: "Staff Basics", detail: "Learn the five lines, four spaces, ledger lines, and ledger spaces." },
      { title: "Treble Clef", detail: "Understand the G clef and its second-line G4 reference." },
      { title: "Bass Clef", detail: "Understand the F clef and its fourth-line F3 reference." },
      { title: "C Clef", detail: "Recognize alto and tenor clefs in practical use." },
      { title: "Grand Staff", detail: "Understand the two-staff system used by keyboard instruments." },
      { title: "Middle C on Two Staves", detail: "Understand the same pitch written in different staff positions." },
    ],
    keyPoints: [
      "Treble-clef line and space note names.",
      "Bass-clef line and space note names.",
      "Two common positions of middle C on the grand staff.",
      "The common forms of C clef.",
    ],
    difficultPoints: [
      "Reading unfamiliar ledger-line notes quickly.",
      "Converting one pitch between different clefs.",
      "Understanding that the C clef always points to middle C.",
    ],
    inClassExercises: [
      "Write all treble-clef line and space notes using a memory aid.",
      "Write all bass-clef line and space notes using a memory aid.",
      "Identify notes on upper and lower ledger lines in treble clef.",
      "Rewrite the melody C4-D4-E4-F4-G4 in bass clef.",
    ],
    homework: [
      "Concept chart: summarize treble, bass, and C clef reference points and common instruments.",
      "Rule application: write middle C and adjacent notes on the staff and label their clef-dependent positions.",
      "Short analysis: compare reading habits and range display in treble and bass clefs.",
    ],
  },
  L4: {
    lessonId: "L4",
    lessonNumber: 4,
    chapterId: "ch2",
    chapter: "Chapter 2 - Notation",
    lessonTitle: "Notation of Notes and Rests",
    knowledgePoints: [
      { title: "Parts of a Note", detail: "Identify notehead, stem, and flag." },
      { title: "Note-Value System", detail: "Understand binary duration relationships from whole notes to thirty-second notes." },
      { title: "Stem Direction", detail: "Apply the rule for stems above and below the middle line." },
      { title: "Dots and Double Dots", detail: "Calculate added one-half and three-quarters of a value." },
      { title: "Rests", detail: "Recognize common rest shapes and their durations." },
      { title: "Tuplets and Ties", detail: "Understand triplet notation and the contexts where ties are needed." },
    ],
    keyPoints: [
      "Duration relationships between notes and rests.",
      "Rules for stem direction.",
      "Calculating dotted-note values.",
      "Writing and performing triplets.",
    ],
    difficultPoints: [
      "Distinguishing ties from slurs.",
      "Calculating double-dotted values.",
      "Feeling triplets in different meters.",
    ],
    inClassExercises: [
      "Fill in: 1 whole note = __ half notes = __ quarter notes = __ eighth notes.",
      "Calculate: dotted half note = __ beats; double-dotted quarter note = __ beats.",
      "Decide stem direction for A4, E4, C5, G4, F5, and D4.",
      "Use ties to write a five-beat D4 across a barline in 4/4.",
    ],
    homework: [
      "Concept chart: create a note-rest duration table from whole note to thirty-second note.",
      "Rule application: complete four dotted, double-dotted, and triplet calculations with steps.",
      "Short analysis: explain why a tie is needed for a long note crossing a beat or barline.",
    ],
  },
  L5: {
    lessonId: "L5",
    lessonNumber: 5,
    chapterId: "ch3",
    chapter: "Chapter 3 - Ornaments and Performance Symbols",
    lessonTitle: "Ornaments",
    knowledgePoints: [
      { title: "Definition of Ornament", detail: "Understand ornaments as small notes or signs that enrich melody." },
      { title: "Trill", detail: "Learn rapid alternation between the main note and the upper neighbor." },
      { title: "Upper Mordent", detail: "Understand main-upper-main execution." },
      { title: "Lower Mordent", detail: "Understand main-lower-main execution." },
      { title: "Turn", detail: "Learn the four-note upper-main-lower-main pattern." },
      { title: "Appoggiatura and Grace Note", detail: "Distinguish their placement and duration treatment." },
    ],
    keyPoints: [
      "Execution order for trills, mordents, and turns.",
      "Duration differences between appoggiaturas and grace notes.",
      "Direction differences between upper and lower mordents.",
      "Recognizing ornament signs in the score.",
    ],
    difficultPoints: [
      "The Baroque practice of beginning some trills from the upper auxiliary note.",
      "Long appoggiaturas taking part of the main note's value.",
      "Different turn placements and execution.",
    ],
    inClassExercises: [
      "Write the execution order for a G4 trill in a Classical-style context.",
      "Write the execution order for upper and lower mordents on F4.",
      "Write the four notes of a turn on D5.",
      "Distinguish the notation of appoggiatura and grace note.",
    ],
    homework: [
      "Concept chart: define trill, upper mordent, lower mordent, turn, and appoggiatura with symbol and execution.",
      "Rule application: design two ornaments in a four-bar melody and justify each choice.",
      "Short analysis: compare Baroque and Classical ornament practices.",
    ],
  },
  L6: {
    lessonId: "L6",
    lessonNumber: 6,
    chapterId: "ch3",
    chapter: "Chapter 3 - Ornaments and Performance Symbols",
    lessonTitle: "Articulation and Score Analysis",
    knowledgePoints: [
      { title: "Dynamic Markings", detail: "Learn the full dynamic scale from ppp to fff." },
      { title: "Crescendo and Diminuendo", detail: "Distinguish gradual changes from sforzando." },
      { title: "Legato", detail: "Recognize smooth connection under a slur." },
      { title: "Staccato", detail: "Understand shortened, separated articulation." },
      { title: "Tenuto", detail: "Understand full value with slight emphasis." },
      { title: "Accent", detail: "Understand emphasis within a phrase." },
    ],
    keyPoints: [
      "The order of the eight basic dynamic levels.",
      "Performance differences among legato, staccato, and tenuto.",
      "Basic ranges of common Italian tempo terms.",
      "Musical meaning of expressive terms.",
    ],
    difficultPoints: [
      "Distinguishing tenuto, legato, and staccato.",
      "Subtle differences between accent and sforzando.",
      "Controlling gradual dynamic changes.",
    ],
    inClassExercises: [
      "Order the dynamics from softest to loudest: mf, ppp, p, fff, mp, ff, pp, f.",
      "Translate Adagio, Andante, Allegro, and Presto into tempo categories.",
      "Analyze dynamics, tempo, and articulation in a familiar piece.",
      "Add suitable performance directions to a four-bar melody.",
    ],
    homework: [
      "Concept chart: classify dynamics, tempo, articulation, and expression symbols.",
      "Rule application: mark a melody with dynamics, tempo, and articulation and explain your choices.",
      "Short analysis: compare legato, staccato, and tenuto in sound and notation.",
    ],
  },
  L7: {
    lessonId: "L7",
    lessonNumber: 7,
    chapterId: "ch4",
    chapter: "Chapter 4 - Abbreviations and Musical Terms",
    lessonTitle: "Abbreviation and Performance Marks",
    knowledgePoints: [
      { title: "Repeat Signs", detail: "Understand repeat barlines and percent-repeat signs." },
      { title: "D.C. and D.S.", detail: "Distinguish returning to the beginning from returning to the sign." },
      { title: "Coda and Fine", detail: "Understand ending points and coda destinations." },
      { title: "First and Second Endings", detail: "Apply Volta brackets to actual performance order." },
      { title: "Octave Signs", detail: "Understand 8va, 8vb, and 15ma displacement." },
      { title: "Tremolo Signs", detail: "Distinguish tremolo from ornaments and repeat shorthand." },
    ],
    keyPoints: [
      "Reading repeat signs correctly.",
      "Combining D.C., D.S., Coda, and Fine.",
      "Performance order for first and second endings.",
      "Direction and meaning of 8va and 8vb.",
    ],
    difficultPoints: [
      "Tracing complex routes such as D.S. al Coda.",
      "Distinguishing tremolo from trill.",
      "Relating stem slashes to subdivision.",
    ],
    inClassExercises: [
      "Explain how to perform D.C. al Fine and D.S. al Coda.",
      "Trace the order A B segno C D D.S. al Fine when Fine appears at C.",
      "Explain two slashes on a quarter-note stem.",
      "Explain 8va, 8vb, 15ma, and loco.",
    ],
    homework: [
      "Concept chart: create a table of common abbreviation and navigation signs.",
      "Rule application: design a mini form using repeats, first/second endings, Coda, or Fine.",
      "Short analysis: trace the performance route of a score with D.C. or D.S.",
    ],
  },
  L8: {
    lessonId: "L8",
    lessonNumber: 8,
    chapterId: "ch4",
    chapter: "Chapter 4 - Abbreviations and Musical Terms",
    lessonTitle: "Musical Terms and Score Reading",
    knowledgePoints: [
      { title: "Tempo Terms", detail: "Learn the system from Largo to Prestissimo with approximate BPM ranges." },
      { title: "Tempo Changes", detail: "Recognize accel., rit., a tempo, and stringendo." },
      { title: "Dynamic Terms", detail: "Organize common Italian dynamic vocabulary." },
      { title: "Expression Terms", detail: "Understand dolce, cantabile, espressivo, and related instructions." },
      { title: "German and French Terms", detail: "Notice native-language markings in German and French repertoire." },
      { title: "Memory Strategies", detail: "Use classification and spaced repetition to learn musical terms." },
    ],
    keyPoints: [
      "Speed ranges of Italian tempo terms.",
      "Meaning of common expression terms.",
      "Why Italian became the international music language.",
      "Using spaced repetition for term memory.",
    ],
    difficultPoints: [
      "Distinguishing similar terms such as Andante and Andantino.",
      "Relating German and French terms to Italian categories.",
      "Interpreting several terms in the same score.",
    ],
    inClassExercises: [
      "Translate Adagio, Andante, Allegro, and Presto with approximate BPM categories.",
      "Explain dolce e cantabile and con brio e maestoso.",
      "Choose a classical work and identify all Italian terms in the score.",
      "Add complete performance directions to a four-bar melody.",
    ],
    homework: [
      "Concept chart: create term cards for tempo, dynamics, expression, and articulation.",
      "Rule application: add performance terms to a score and explain each function.",
      "Short analysis: explain how several terms shape the style of one piece.",
    ],
  },
  L9: {
    lessonId: "L9",
    lessonNumber: 9,
    chapterId: "ch5",
    chapter: "Chapter 5 - Rhythm and Meter",
    lessonTitle: "Rhythm and Meter",
    knowledgePoints: [
      { title: "Four Core Concepts", detail: "Distinguish beat, rhythm, meter, and time signature." },
      { title: "Meaning of Time Signature", detail: "Understand top number as beat count and bottom number as beat unit." },
      { title: "Common Meters", detail: "Learn accent patterns in 2/4, 3/4, 4/4, and 6/8." },
      { title: "Simple and Compound Meter", detail: "Understand duple subdivision versus triple subdivision of each beat." },
      { title: "Barlines", detail: "Recognize single, double, final, and repeat barlines." },
      { title: "Conducting Patterns", detail: "Connect common meters with conducting gestures." },
    ],
    keyPoints: [
      "Distinguishing the four core rhythm terms.",
      "Accent patterns in common meters.",
      "The essential difference between simple and compound meter.",
      "Finding strong beats.",
    ],
    difficultPoints: [
      "Distinguishing 6/8 from 3/4.",
      "Understanding compound meter by larger beats.",
      "Accent patterns in mixed meters such as 5/8 and 7/8.",
    ],
    inClassExercises: [
      "Classify 2/4, 3/4, 4/4, 6/8, 9/8, and 12/8 as simple or compound.",
      "Mark the full accent pattern in 4/4.",
      "Explain the essential difference between 6/8 and 3/4.",
      "Practice conducting gestures for 2/4, 3/4, and 4/4.",
    ],
    homework: [
      "Concept chart: explain beat, rhythm, meter, and time signature in your own words.",
      "Rule application: write accent patterns and beat feel for 2/4, 3/4, 4/4, and 6/8.",
      "Short analysis: compare 6/8 and 3/4 in feel, accent, and grouping.",
    ],
  },
  L10: {
    lessonId: "L10",
    lessonNumber: 10,
    chapterId: "ch5",
    chapter: "Chapter 5 - Rhythm and Meter",
    lessonTitle: "Note Grouping in Different Meters",
    knowledgePoints: [
      { title: "Core Grouping Principle", detail: "Keep beats clear inside the measure and boundaries visible between beats." },
      { title: "Grouping in Simple Meter", detail: "Understand beat-based grouping in 2/4, 3/4, and 4/4." },
      { title: "Special 4/4 Rule", detail: "Avoid hiding the middle of the measure." },
      { title: "Grouping in Compound Meter", detail: "Group 6/8, 9/8, and 12/8 by large beats." },
      { title: "Ties Across Barlines", detail: "Use ties when sustained values cross a barline." },
      { title: "Beams and Flags", detail: "Use beaming to preserve rhythmic clarity." },
    ],
    keyPoints: [
      "Beat clarity as the main grouping principle.",
      "The mid-measure boundary in 4/4.",
      "The 3+3 grouping rule in 6/8.",
      "Correct use of cross-bar ties.",
    ],
    difficultPoints: [
      "Knowing when to split a note to avoid crossing a beat.",
      "Distinguishing 6/8 grouping from 3/4 grouping.",
      "Maintaining visual clarity in complex rhythms.",
    ],
    inClassExercises: [
      "Judge whether eight eighth notes in 4/4 should be beamed as one group.",
      "Write a six-beat G4 in 4/4 using ties.",
      "Group six eighth notes correctly in 6/8.",
      "Rewrite a rhythm that hides the mid-measure boundary.",
    ],
    homework: [
      "Concept chart: compare note grouping in simple and compound meters.",
      "Rule application: write two clean measures in 4/4 and 6/8 and explain the grouping.",
      "Short analysis: correct an unclear rhythm and explain why the revision is better.",
    ],
  },
  L11: {
    lessonId: "L11",
    lessonNumber: 11,
    chapterId: "ch5",
    chapter: "Chapter 5 - Rhythm and Meter",
    lessonTitle: "Syncopation and Syncopated Rhythm",
    knowledgePoints: [
      { title: "Definition of Syncopation", detail: "Understand accent displacement from a strong beat to a weak beat or weak part." },
      { title: "Weak-Beat Extension", detail: "Use ties to carry a weak beat into a strong beat." },
      { title: "Off-Beat Accent", detail: "Understand accents placed on weak positions." },
      { title: "Rest on Strong Beat", detail: "Create syncopation by leaving a strong beat silent." },
      { title: "Short-Long-Short Pattern", detail: "Recognize the classic eighth-quarter-eighth syncopation." },
      { title: "Style Applications", detail: "Understand syncopation in different musical styles." },
    ],
    keyPoints: [
      "Syncopation as accent displacement.",
      "Three basic forms of syncopation.",
      "The classic short-long-short pattern.",
      "How syncopation functions in different styles.",
    ],
    difficultPoints: [
      "Performing syncopation without rushing.",
      "Distinguishing notated syncopation from expressive accenting.",
      "Keeping a steady beat while emphasizing syncopated notes.",
    ],
    inClassExercises: [
      "Explain the essence of syncopation in your own words.",
      "Identify three different forms of syncopation.",
      "Clap a regular rhythm and a syncopated rhythm for comparison.",
      "Create a four-bar syncopated rhythm in 4/4.",
    ],
    homework: [
      "Concept chart: summarize the notation, accent shift, and sound of three syncopation forms.",
      "Rule application: write two syncopated rhythms in 4/4 and mark the displaced accents.",
      "Short analysis: explain how syncopation increases groove or expression in a familiar style.",
    ],
  },
  L12: {
    lessonId: "L12",
    lessonNumber: 12,
    chapterId: "ch5",
    chapter: "Chapter 5 - Rhythm and Meter",
    lessonTitle: "Integrated Review and Post-Test",
    knowledgePoints: [
      { title: "Chapter 1 Review", detail: "Review sound properties, scales, temperament, and harmonics." },
      { title: "Chapter 2 Review", detail: "Review clefs, staves, notes, and rests." },
      { title: "Chapter 3 Review", detail: "Review ornaments, dynamics, articulation, and performance symbols." },
      { title: "Chapter 4 Review", detail: "Review abbreviations and Italian musical terms." },
      { title: "Chapter 5 Review", detail: "Review time signatures, note grouping, and syncopation." },
      { title: "Post-Test Procedure", detail: "Understand the music theory post-test, motivation survey, and technology acceptance survey." },
    ],
    keyPoints: [
      "Connecting the five major course chapters.",
      "Identifying and strengthening weak areas.",
      "Building an integrated music theory framework.",
      "Preparing for later intermediate music theory study.",
    ],
    difficultPoints: [
      "Seeing links across knowledge points.",
      "Applying several concepts in one real score.",
      "Clarifying final confusions such as tie versus slur and tremolo versus trill.",
    ],
    inClassExercises: [
      "Complete the 50-item music theory post-test.",
      "Complete the 36-item IMMS motivation survey.",
      "Complete the 13-item TAM technology acceptance survey.",
      "Choose a complete work and conduct integrated score analysis.",
    ],
    homework: [
      "Concept chart: list two strongest and two weakest knowledge points in each chapter.",
      "Rule application: use post-test results to create a next-stage review plan.",
      "Short analysis: analyze one complete work across clef, terms, meter, and ornaments.",
    ],
  },
};

function kp(id, lessonId, chapterId, title, subConcepts, easy, medium, hard, facts, comparisons, exerciseTypes = ["AI Tutor Q&A", "Adaptive practice"]) {
  return { id, lessonId, chapterId, title, subConcepts, exerciseTypes, easy, medium, hard, facts, comparisons };
}

export const ENGLISH_KNOWLEDGE_POINTS = [
  kp(
    "L1_K1_pitchProperties",
    "L1",
    "ch1",
    "Four Properties of Sound",
    ["Pitch is determined by frequency in hertz", "Duration is determined by how long vibration lasts", "Loudness is determined by amplitude", "Timbre is shaped by the harmonic spectrum", "A4 = 440 Hz is the international reference pitch"],
    ["Identify which property controls pitch", "Recall the A4 reference frequency", "Match terms with sound properties"],
    ["Explain why piano and violin sound different on the same pitch", "Connect amplitude with loudness", "Apply the concepts to an audio example"],
    ["Calculate octave-related frequencies", "Analyze one tone across all four properties", "Explain timbre using harmonics"],
    ["Pitch rises when frequency increases.", "Duration describes how long a sound lasts.", "Amplitude affects perceived loudness.", "Timbre depends on harmonic content.", "A4 is commonly standardized at 440 Hz."],
    ["Pitch versus loudness: frequency and amplitude are different properties.", "Same pitch on piano and violin: frequency can match while timbre differs.", "A4 versus A5: frequency doubles across the octave.", "Duration versus timbre: time length and sound color describe different aspects.", "Loud playing versus soft playing: amplitude changes while pitch can stay fixed."],
  ),
  kp(
    "L1_K2_wholeStepHalfStep",
    "L1",
    "ch1",
    "Whole Steps and Half Steps",
    ["A half step is the smallest common pitch distance", "A whole step equals two half steps", "Natural half steps are E-F and B-C", "Keyboard adjacency helps identify half steps", "The major-scale pattern is W-W-H-W-W-W-H"],
    ["Distinguish C-D from C-C sharp", "Recognize E-F and B-C as natural half steps", "Identify adjacent keyboard notes"],
    ["Apply accidentals in step judgments", "Use the major-scale pattern", "Compare basic and altered pitch pairs"],
    ["Infer steps across octaves", "Handle unusual spellings", "Derive a complete major scale"],
    ["A half step is the smallest step unit on the keyboard.", "A whole step contains two half steps.", "E-F and B-C are natural half steps.", "C-D, D-E, F-G, G-A, and A-B are whole steps in basic white-key motion.", "The natural major scale follows W-W-H-W-W-W-H."],
    ["Natural half step versus chromatic half step: both are half steps but are spelled differently.", "Whole step versus half step: two semitones versus one semitone.", "E-F versus C-D: no black key versus one black key between them.", "Major scale versus minor scale: different whole/half-step patterns.", "C major versus G major: same pattern from a different starting note."],
    ["Interval exercise", "Pitch identification"],
  ),
  kp(
    "L2_K1_octaveGroups",
    "L2",
    "ch1",
    "Octave Grouping and Middle C",
    ["Octave labels organize pitch register", "Middle C is C4", "Middle C is also c1 in some notation systems", "Middle C sits between treble and bass staves", "Its frequency is about 261.63 Hz"],
    ["Locate middle C", "Identify basic octave labels", "Recognize nearby register groups"],
    ["Match keyboard, staff, and octave labels", "Use grand staff locations", "Relate register with frequency"],
    ["Read across several registers", "Handle rare low and high labels", "Map register to keyboard range"],
    ["Middle C is commonly written as C4.", "Middle C is about 261.63 Hz.", "Octave labels organize repeated pitch names by register.", "Middle C appears below the treble staff and above the bass staff.", "Register naming changes as pitch crosses each octave boundary."],
    ["Treble middle C versus bass middle C: the same pitch appears in different staff positions.", "C4 versus C5: same pitch class, one octave apart.", "Upper register versus lower register: frequency is higher in the upper register.", "Staff location versus keyboard location: both refer to the same pitch but use different visual systems.", "Octave label versus pitch name: C is the class, C4 is a specific register."],
    ["Notation exercise", "AI Tutor Q&A"],
  ),
  kp(
    "L2_K2_temperamentEnharmonic",
    "L2",
    "ch1",
    "Temperament and Enharmonic Equivalence",
    ["Equal temperament divides the octave into 12 equal semitones", "Just intonation uses simple harmonic ratios", "Pythagorean tuning is based on fifth generation", "Enharmonic spellings such as C-sharp and D-flat can sound the same", "Spelling choices depend on tonal context"],
    ["Recognize C-sharp and D-flat as enharmonic", "Name three tuning systems", "Define enharmonic equivalence"],
    ["Compare tuning systems", "Recognize E-sharp/F and B-sharp/C", "Explain contextual pitch spelling"],
    ["Choose spelling in a tonal passage", "Connect harmonic ratios with tuning", "Use the harmonic series to explain tuning"],
    ["Equal temperament divides the octave into twelve equal parts.", "Just intonation prioritizes simple frequency ratios.", "Pythagorean tuning builds pitches through pure fifths.", "Enharmonic notes can share the same sounding pitch in equal temperament.", "Pitch spelling can reflect harmonic or tonal function."],
    ["Equal temperament versus just intonation: equal spacing versus ratio purity.", "C-sharp versus D-flat: same key on piano but different theoretical spelling.", "Pythagorean tuning versus equal temperament: generated fifths versus equal semitones.", "Enharmonic sound versus notation function: hearing may match while meaning differs.", "Temperament versus timbre: pitch system versus sound color."],
  ),
  kp(
    "L3_K1_trebleClef",
    "L3",
    "ch2",
    "Treble Clef Reading",
    ["The treble clef is the G clef", "The second line is G4", "Line notes are E-G-B-D-F", "Space notes are F-A-C-E", "Ledger lines extend the staff"],
    ["Name basic treble staff notes", "Locate G4", "Identify middle C below the staff"],
    ["Read simple ledger-line notes", "Use reference points", "Read short treble melodies"],
    ["Read across register changes", "Use ledger lines fluently", "Convert note locations into pitch names"],
    ["The treble clef centers on second-line G4.", "Treble line notes from bottom to top are E, G, B, D, F.", "Treble space notes from bottom to top are F, A, C, E.", "Middle C is on the ledger line below the treble staff.", "Ledger lines extend the five-line staff system."],
    ["Line notes versus space notes: the notehead position changes the pitch.", "G4 reference versus counting from the bottom: reference reading is faster.", "Treble clef versus bass clef: each has a different anchor note.", "Middle C in treble versus bass: same pitch, different staff location.", "Ledger-line reading versus inside-staff reading: both follow the same alphabet sequence."],
    ["Staff-reading tasks", "Notation recognition"],
  ),
  kp(
    "L3_K2_bassClef",
    "L3",
    "ch2",
    "Bass Clef Reading",
    ["The bass clef is the F clef", "The fourth line is F3", "Line notes are G-B-D-F-A", "Space notes are A-C-E-G", "Middle C appears above the bass staff"],
    ["Name basic bass staff notes", "Locate F3", "Identify middle C above the staff"],
    ["Read simple ledger-line notes", "Use F3 as a reference", "Read short bass melodies"],
    ["Read lower-register passages", "Integrate bass clef with grand staff reading", "Convert bass staff positions into pitch names"],
    ["The bass clef locates F3 on the fourth line.", "Bass line notes from bottom to top are G, B, D, F, A.", "Bass space notes from bottom to top are A, C, E, G.", "Middle C is on the ledger line above the bass staff.", "Bass clef is used for lower-register notation."],
    ["Bass clef versus treble clef: F-clef anchor versus G-clef anchor.", "Middle C above bass versus below treble: same pitch in two locations.", "Line notes versus space notes: different staff positions create different pitch names.", "Reference-point reading versus rote counting: anchor notes reduce errors.", "Grand staff reading integrates treble and bass systems."],
    ["Staff-reading tasks", "Notation recognition"],
  ),
  kp(
    "L4_K1_noteValues",
    "L4",
    "ch2",
    "Note-Value System",
    ["Whole, half, quarter, eighth, and sixteenth values", "Each shorter value is half of the previous one", "Rests have matching durations", "Notehead, stem, and flag form the note symbol", "Beat counting depends on meter"],
    ["Recognize common note values", "Convert whole to half and quarter notes", "Identify matching rests"],
    ["Calculate mixed durations", "Read note and rest combinations", "Apply note values in a measure"],
    ["Solve complex rhythm totals", "Use thirty-second values", "Combine notes and rests accurately"],
    ["A whole note commonly equals four quarter-note beats in 4/4.", "A half note is half of a whole note.", "A quarter note is one beat in 4/4.", "Eighth and sixteenth notes subdivide the beat.", "Rests represent silence with specific duration."],
    ["Note versus rest: sound versus silence with comparable duration.", "Quarter note versus eighth note: one beat versus half beat in 4/4.", "Flagged notes versus beamed notes: different notation for the same subdivision.", "Duration value versus tempo: note value is relative, tempo sets speed.", "Whole note versus whole rest: both can fill a full 4/4 measure."],
    ["Rhythm-value tasks", "Counting exercises"],
  ),
  kp(
    "L4_K2_dotsAndTies",
    "L4",
    "ch2",
    "Dots and Ties",
    ["A dot adds half of the original value", "A double dot adds three quarters of the original value", "A tie connects same-pitch notes into one duration", "Ties can cross beats or barlines", "Triplets divide a value into three equal parts"],
    ["Calculate a dotted quarter note", "Recognize a tie", "Distinguish simple dotted values"],
    ["Calculate double-dotted values", "Identify triplets", "Use ties across beats"],
    ["Resolve dotted and tied rhythms across measures", "Distinguish tie from slur", "Notate sustained values clearly"],
    ["A dotted note adds half of the original value.", "A double-dotted note adds one-half plus one-quarter of the original value.", "A tie joins notes of the same pitch.", "A slur connects notes for phrasing, not duration extension.", "Triplets divide a beat into three equal parts."],
    ["Dot versus tie: adding value to one note versus connecting two notes.", "Tie versus slur: duration extension versus articulation phrase.", "Single dot versus double dot: one-half addition versus three-quarter addition.", "Triplet versus two eighths: three equal parts versus two equal parts.", "Across-beat tie versus within-beat dotted note: notation depends on metric clarity."],
    ["Rhythm calculation", "Notation correction"],
  ),
  kp(
    "L5_K1_trillMordent",
    "L5",
    "ch3",
    "Trills and Mordents",
    ["A trill rapidly alternates with the upper neighbor", "An upper mordent moves main-upper-main", "A lower mordent moves main-lower-main", "Execution can depend on style period", "Auxiliary-note direction is essential"],
    ["Recognize trill and mordent signs", "Name the main execution direction", "Distinguish upper and lower mordent"],
    ["Explain execution order", "Apply ornament direction in context", "Consider Baroque versus Classical habits"],
    ["Choose execution in a score", "Handle chromatic auxiliary notes", "Compare similar ornament signs"],
    ["A trill is often marked tr.", "An upper mordent moves to the upper neighbor and back.", "A lower mordent moves to the lower neighbor and back.", "Some Baroque trills begin from the upper auxiliary note.", "Ornament execution depends on pitch context and style."],
    ["Trill versus mordent: repeated alternation versus a short three-note figure.", "Upper mordent versus lower mordent: opposite auxiliary direction.", "Baroque versus Classical execution: style changes starting-note conventions.", "Written sign versus performed notes: one symbol may imply several sounding notes.", "Ornament versus main melody: decoration enriches but does not replace the structural tone."],
    ["Symbol recognition", "Performance-meaning tasks"],
  ),
  kp(
    "L5_K2_turnAppoggiatura",
    "L5",
    "ch3",
    "Turns and Appoggiaturas",
    ["A turn usually moves upper-main-lower-main", "An inverted turn reverses the direction", "An appoggiatura leans into the main note", "A grace note is played quickly around the main note", "Ornament placement affects timing"],
    ["Recognize turn and appoggiatura symbols", "Describe a turn as four-note motion", "Distinguish small-note ornaments"],
    ["Calculate appoggiatura timing", "Explain inverted turn direction", "Apply ornaments in a melodic context"],
    ["Interpret complex ornament placement", "Compare long and short appoggiaturas", "Choose execution by style"],
    ["A regular turn normally uses upper-main-lower-main motion.", "An inverted turn reverses that contour.", "An appoggiatura takes expressive time from the main note.", "A grace note is usually brief.", "The printed position of an ornament can affect when it is performed."],
    ["Turn versus mordent: four-note surround versus quick neighbor motion.", "Appoggiatura versus grace note: expressive leaning tone versus rapid decoration.", "Regular turn versus inverted turn: opposite contour.", "Written small note versus main note: visual size indicates ornamental status.", "Placement above a note versus between notes: timing can change."],
    ["Symbol recognition", "Score-analysis tasks"],
  ),
  kp(
    "L6_K1_dynamics",
    "L6",
    "ch3",
    "Dynamic Markings",
    ["p and f mark soft and loud levels", "Dynamic levels range from very soft to very loud", "Crescendo means gradually louder", "Diminuendo means gradually softer", "Sforzando means a sudden accent"],
    ["Recognize p, f, mp, and mf", "Order basic dynamic levels", "Identify crescendo and diminuendo"],
    ["Explain sfz and fp", "Interpret dynamic changes in context", "Use hairpin symbols"],
    ["Analyze dynamic design in a passage", "Interpret uncommon extremes", "Combine dynamic and expressive markings"],
    ["p means soft and f means loud.", "mp means moderately soft and mf means moderately loud.", "crescendo means gradually louder.", "diminuendo means gradually softer.", "sfz indicates a sudden strong emphasis."],
    ["p versus f: soft versus loud.", "crescendo versus diminuendo: increasing versus decreasing loudness.", "sfz versus accent: sudden force versus local emphasis.", "Dynamic marking versus tempo marking: loudness versus speed.", "Written dynamic versus performed balance: notation guides but context shapes sound."],
    ["Symbol recognition", "Score interpretation"],
  ),
  kp(
    "L6_K2_articulation",
    "L6",
    "ch3",
    "Articulation Markings",
    ["Legato connects notes smoothly", "Staccato separates notes shortly", "Tenuto sustains the note value", "Accent emphasizes attack", "Slurs shape phrasing and connection"],
    ["Recognize legato, staccato, and tenuto", "Match symbols with performance effect", "Identify an accent"],
    ["Distinguish legato from slur context", "Compare staccato and tenuto", "Apply articulation to a short phrase"],
    ["Interpret combined articulation and dynamics", "Handle instrument-specific articulation", "Analyze style-appropriate articulation"],
    ["Legato means smooth connection.", "Staccato means detached and shortened.", "Tenuto means held for full value with slight weight.", "Accent emphasizes the beginning of a note.", "A slur often indicates connected phrasing."],
    ["Legato versus staccato: connected versus detached.", "Tenuto versus staccato: sustained versus shortened.", "Accent versus sforzando: local emphasis versus forceful stress.", "Slur versus tie: phrasing across different notes versus duration across same pitch.", "Articulation versus dynamics: attack/connection versus loudness."],
    ["Symbol recognition", "Performance interpretation"],
  ),
  kp(
    "L7_K1_repeatSigns",
    "L7",
    "ch4",
    "Repeat Signs",
    ["Repeat barlines mark sections to repeat", "First and second endings change the second pass", "Percent signs can repeat previous measures", "bis and ter may mark repeated times", "Performance order must be traced carefully"],
    ["Recognize repeat barlines", "Understand first and second endings", "Trace a simple repeat"],
    ["Apply multiple endings", "Interpret repeat counts", "Use percent repeats"],
    ["Trace complex repeat structures", "Resolve multi-ending forms", "Apply repeats in a full score"],
    ["Repeat barlines show where a passage repeats.", "First ending is used on the first pass and second ending on the repeat.", "Percent-repeat symbols can abbreviate repeated measures.", "Performance order depends on both signs and endings.", "Repeat instructions reduce rewriting in the score."],
    ["Simple repeat versus first/second endings: same material versus changed endings.", "Repeat barline versus D.C.: local repetition versus return to the beginning.", "Percent repeat versus written-out measure: abbreviation versus explicit notation.", "First ending versus second ending: different route on each pass.", "Notation shortcut versus actual performance: the player must unfold the route."],
    ["Score-navigation tasks", "Symbol recognition"],
  ),
  kp(
    "L7_K2_dcDsCoda",
    "L7",
    "ch4",
    "D.C., D.S., Coda, and Fine",
    ["D.C. means return to the beginning", "D.S. means return to the sign", "Fine marks the ending", "Coda marks a final section", "al Fine and al Coda combine navigation instructions"],
    ["Identify D.C., D.S., Coda, and Fine", "Explain return points", "Trace a short route"],
    ["Apply D.C. al Fine", "Apply D.S. al Coda", "Recognize segno and coda signs"],
    ["Trace combined navigation instructions", "Handle multiple codas", "Resolve full-score playback order"],
    ["D.C. stands for Da Capo, from the head.", "D.S. stands for Dal Segno, from the sign.", "Fine means finish here.", "Coda is a concluding section.", "al Coda directs the performer to jump to the coda at the marked point."],
    ["D.C. versus D.S.: beginning versus sign.", "Fine versus Coda: stop point versus ending section.", "D.C. al Fine versus D.S. al Coda: different return and exit logic.", "Repeat signs versus navigation terms: local repeats versus structural jumps.", "Written route versus performed order: navigation symbols must be unfolded."],
    ["Score-navigation tasks", "Term recognition"],
  ),
  kp(
    "L8_K1_tempoTerms",
    "L8",
    "ch4",
    "Tempo Terms",
    ["Largo and Adagio indicate slow tempos", "Andante and Moderato indicate moderate tempos", "Allegro and Presto indicate fast tempos", "rit. slows down", "a tempo returns to the original tempo"],
    ["Recall basic tempo words", "Order slow to fast terms", "Identify tempo changes"],
    ["Match terms with approximate speed categories", "Distinguish tempo from expression", "Interpret accelerando and ritardando"],
    ["Interpret several tempo markings in a score", "Handle uncommon tempo words", "Analyze tempo's musical effect"],
    ["Largo is very slow.", "Adagio is slow.", "Andante is walking pace.", "Allegro is fast and lively.", "Presto is very fast."],
    ["Tempo term versus dynamic marking: speed versus loudness.", "Adagio versus Allegro: slow versus fast.", "ritardando versus accelerando: slowing down versus speeding up.", "a tempo versus tempo change: return versus modification.", "Tempo marking versus expression term: movement speed versus character."],
    ["Term recognition", "Score interpretation"],
  ),
  kp(
    "L8_K2_expressionTerms",
    "L8",
    "ch4",
    "Expression Terms",
    ["dolce means sweetly", "cantabile means in a singing style", "espressivo means expressively", "con brio means with spirit", "maestoso means majestically"],
    ["Recognize common expression terms", "Match terms with character", "Separate expression from tempo"],
    ["Interpret compound expressions", "Connect terms with performance style", "Use expression words in a score"],
    ["Analyze expressive directions in context", "Compare terms across languages", "Choose appropriate expressive instructions"],
    ["dolce asks for a sweet tone.", "cantabile asks for a singing style.", "espressivo asks for expressive playing.", "con brio asks for energy and spirit.", "maestoso asks for a majestic character."],
    ["Expression term versus tempo term: character versus speed.", "dolce versus forte: sweetness versus loudness.", "cantabile versus legato: singing character versus connected articulation.", "con brio versus maestoso: energetic versus majestic.", "Expression marking versus dynamic marking: mood versus volume."],
    ["Term recognition", "Interpretation tasks"],
  ),
  kp(
    "L9_K1_timeSignatureMeter",
    "L9",
    "ch5",
    "Time Signatures and Metric Accents",
    ["Top number gives beats per measure", "Bottom number gives the beat unit", "2/4 has strong-weak accents", "3/4 has strong-weak-weak accents", "4/4 has strong-weak-medium-weak accents"],
    ["Identify beat count and beat unit", "Recognize 2/4, 3/4, and 4/4", "State simple accent patterns"],
    ["Apply accent patterns", "Interpret 6/8 grouping", "Connect meter with style"],
    ["Analyze complex time signatures", "Handle mixed meters", "Trace accents in a passage"],
    ["The top number tells how many beats are in a measure.", "The bottom number tells which note value gets one beat.", "2/4 is commonly strong-weak.", "3/4 is commonly strong-weak-weak.", "4/4 is commonly strong-weak-medium-weak."],
    ["Time signature versus tempo: meter organization versus speed.", "3/4 versus 6/8: three simple beats versus two compound beats.", "Strong beat versus weak beat: metric weight differs.", "Beat unit versus beat count: bottom number versus top number.", "Simple accent pattern versus actual phrasing: meter guides but music can vary."],
    ["Meter-identification tasks", "Rhythm counting"],
  ),
  kp(
    "L9_K2_simpleCompound",
    "L9",
    "ch5",
    "Simple and Compound Meters",
    ["Simple meter subdivides each beat into two", "Compound meter subdivides each beat into three", "6/8 is usually compound duple", "9/8 is usually compound triple", "12/8 is usually compound quadruple"],
    ["Classify common simple meters", "Recognize 6/8 as compound", "Identify beat subdivision"],
    ["Distinguish 6/8 from 3/4", "Find large beats in compound meter", "Classify 9/8 and 12/8"],
    ["Analyze mixed meters", "Handle uncommon meters", "Compare feel across meters"],
    ["Simple meters usually divide each beat into two parts.", "Compound meters usually divide each beat into three parts.", "6/8 is commonly felt as two large beats.", "9/8 is commonly felt as three large beats.", "12/8 is commonly felt as four large beats."],
    ["Simple versus compound meter: duple subdivision versus triple subdivision.", "3/4 versus 6/8: three beats versus two dotted-quarter beats.", "Beat count versus subdivision: top number alone is not enough.", "Compound duple versus compound triple: two large beats versus three large beats.", "Written eighth notes versus felt beats: notation and pulse grouping differ."],
    ["Meter classification", "Rhythm grouping"],
  ),
  kp(
    "L10_K1_noteGrouping",
    "L10",
    "ch5",
    "Note Grouping Rules",
    ["Group notes by beat", "Keep strong beats visually clear", "Avoid hiding the middle of 4/4", "Beam compound meters by large beat", "Use rests and ties for readability"],
    ["Identify correct and incorrect grouping", "Group eighth notes in 4/4", "Recognize beat boundaries"],
    ["Apply 6/8 grouping", "Split notes across the 4/4 midpoint", "Use beaming rules"],
    ["Correct complex grouping errors", "Handle mixed subdivisions", "Preserve meter clarity"],
    ["Grouping should make beats easy to see.", "In 4/4, the middle of the measure should remain visually clear.", "In 6/8, eighth notes are often grouped 3+3.", "Beams can show beat organization.", "Correct grouping supports reading and performance."],
    ["Correct duration versus correct notation: total value alone is not enough.", "4/4 grouping versus 6/8 grouping: 2+2+2+2 versus 3+3 eighth-note organization.", "Beam grouping versus tie use: grouping connects subdivisions while ties sustain notes.", "Strong-beat clarity versus compact notation: readability is the priority.", "Simple meter grouping versus compound meter grouping: beat unit changes the visual logic."],
    ["Notation correction", "Rhythm grouping"],
  ),
  kp(
    "L10_K2_crossBarTies",
    "L10",
    "ch5",
    "Cross-Bar Ties",
    ["Ties connect same-pitch notes", "A sustained value may need to be split at the barline", "Ties preserve metric clarity", "Cross-beat ties clarify strong beats", "A tie is not the same as a slur"],
    ["Recognize when a tie is required", "Identify tied same-pitch notes", "Explain a simple cross-bar tie"],
    ["Use ties across beats", "Use ties across barlines", "Revise unclear sustained values"],
    ["Notate long values across measures", "Distinguish slur and tie in context", "Maintain meter while sustaining sound"],
    ["A tie connects notes of the same pitch into one duration.", "A tie can cross a barline.", "Sustained values are often split to show meter clearly.", "A slur connects different notes for phrasing.", "Cross-bar ties help preserve the measure structure."],
    ["Tie versus slur: same pitch duration versus phrase connection.", "Cross-bar tie versus long note value: split notation can be clearer.", "Cross-beat tie versus dotted note: meter may require a tie.", "Sounding duration versus written grouping: performance may be continuous while notation is split.", "Same-pitch tie versus repeated note: tied notes are not re-attacked."],
    ["Notation correction", "Rhythm analysis"],
  ),
  kp(
    "L11_K1_syncopationTypes",
    "L11",
    "ch5",
    "Three Forms of Syncopation",
    ["Syncopation shifts accent away from the expected strong beat", "A tie can extend a weak beat into a strong beat", "An accent can emphasize a weak position", "A rest can remove the strong beat", "The core effect is accent displacement"],
    ["Recognize off-beat emphasis", "Name three syncopation forms", "Identify the basic concept"],
    ["Classify syncopation forms", "Find displaced accents", "Compare regular and syncopated rhythms"],
    ["Analyze combined syncopation", "Perform syncopation steadily", "Distinguish syncopation from triplets"],
    ["Syncopation changes the expected accent pattern.", "One form extends a weak beat into a strong beat.", "One form accents a weak part of the beat.", "One form rests on a strong beat.", "The main idea is accent displacement."],
    ["Tie syncopation versus rest syncopation: sustained weak beat versus silent strong beat.", "Off-beat accent versus regular accent: emphasis shifts away from the expected point.", "Syncopation versus regular rhythm: displaced versus stable accents.", "Syncopation versus triplet: accent shift versus three-part subdivision.", "Written syncopation versus expressive emphasis: notation versus performance nuance."],
    ["Rhythm identification", "Score analysis"],
  ),
  kp(
    "L11_K2_classicSyncopation",
    "L11",
    "ch5",
    "Classic Syncopation Patterns",
    ["Short-long-short is a common syncopated pattern", "Eighth-quarter-eighth spans two beats", "The long note receives displaced emphasis", "Syncopation appears in jazz, Latin, classical, and pop music", "Pattern recognition helps performance"],
    ["Identify the short-long-short pattern", "Decide whether a rhythm contains syncopation", "Recognize visual features"],
    ["Perform short-long-short syncopation", "Compare forward and backward syncopations", "Connect patterns with style"],
    ["Analyze sixteenth-note syncopations", "Use syncopation in composition", "Recognize hidden syncopation"],
    ["The classic short-long-short pattern is eighth-quarter-eighth.", "Its central long note creates displaced weight.", "Syncopation can be used across many styles.", "Long-short-long patterns create a different feel.", "Recognizing visual patterns supports accurate rhythm reading."],
    ["Short-long-short versus regular eighths: displaced weight versus even pulse.", "Forward syncopation versus backward syncopation: different direction of emphasis.", "Jazz syncopation versus classical syncopation: same device, different style use.", "Basic syncopation versus sixteenth-note syncopation: increasing complexity.", "Pattern recognition versus beat counting: both are needed for performance."],
    ["Rhythm reading", "Pattern recognition"],
  ),
  kp(
    "L12_K1_review",
    "L12",
    "ch5",
    "Integrated Review 1",
    ["Review sound properties, scales, and temperament", "Review clefs, staff reading, notes, and rests", "Connect chapters 1-3", "Locate weak knowledge points", "Apply concepts in mixed tasks"],
    ["Recall core terms", "Review basic definitions", "Identify the relevant chapter"],
    ["Apply concepts across pitch and notation tasks", "Solve mixed questions", "Explain common confusions"],
    ["Synthesize several concepts in score analysis", "Diagnose errors by knowledge point", "Plan targeted review"],
    ["Sound properties, whole/half steps, temperament, clefs, and note values are core early-course concepts.", "Integrated review requires choosing the right concept for each task.", "Error patterns help identify weak knowledge points.", "Mixed tasks connect pitch, notation, rhythm, and score symbols.", "Review should prioritize weak points rather than repeating all content equally."],
    ["Pitch concept versus notation concept: sound property versus written representation.", "Clef reading versus note-value reading: pitch location versus duration.", "Temperament versus enharmonic spelling: pitch system versus notation choice.", "Recall versus application: naming a concept versus using it in a score.", "Weak-point review versus full rereading: targeted review is more efficient."],
    ["Integrated diagnostic items", "AI Tutor Q&A"],
  ),
  kp(
    "L12_K2_review",
    "L12",
    "ch5",
    "Integrated Review 2",
    ["Review ornaments, dynamics, articulation, and terms", "Review meter, grouping, ties, and syncopation", "Connect chapters 4-5", "Use diagnostic feedback", "Prepare for the post-test"],
    ["Recall core symbols and terms", "Identify the required knowledge point", "Review basic rhythm rules"],
    ["Solve cross-lesson application tasks", "Compare similar symbols", "Interpret score context"],
    ["Evaluate complex integrated examples", "Explain a full performance route", "Plan next-stage study"],
    ["Later-course review connects ornaments, performance signs, musical terms, meter, grouping, and syncopation.", "Diagnostic tasks should reveal which knowledge point is needed.", "Similar symbols must be separated by function.", "Rhythm notation should preserve meter clarity.", "Post-test preparation should combine recall and application."],
    ["Ornament versus articulation: decorative pitch motion versus note connection or attack.", "Tempo term versus expression term: speed versus character.", "Tie versus slur: sustained same pitch versus phrasing.", "Repeat route versus coda route: local repeat versus structural jump.", "Syncopation versus regular grouping: displaced accent versus clear metric placement."],
    ["Integrated diagnostic items", "Mixed practice"],
  ),
];

export const ENGLISH_WEAK_KNOWLEDGE_ENHANCEMENTS = Object.fromEntries(
  ENGLISH_KNOWLEDGE_POINTS
    .filter((point) => point.lessonId !== "L12")
    .map((point) => [
      point.id,
      {
        explanation: `Focus on the central rule for ${point.title}. First identify what the question is asking, then connect it to the score or sound example before choosing an answer.`,
        misunderstandings: [
          `Confusing ${point.title} with a nearby concept from the same lesson.`,
          "Answering from memorized vocabulary without checking the musical context.",
          "Ignoring the visual or aural clue that identifies the correct rule.",
        ],
        practiceGuide: [
          "Name the concept first, then apply the rule.",
          "Check the staff, keyboard, rhythm, or term context before answering.",
          "When uncertain, compare the correct option with one close distractor.",
        ],
        correctionQuestions: [
          {
            prompt: `What is the safest first step when solving a ${point.title} question?`,
            options: ["Identify the concept and context", "Guess from the longest option", "Ignore the notation", "Skip the rule"],
            answer: "Identify the concept and context",
            explanation: "The demo review flow is built around concept identification followed by rule application.",
          },
          {
            prompt: `Which strategy best supports mastery of ${point.title}?`,
            options: ["Practice with feedback", "Memorize only the title", "Avoid mixed examples", "Change the lesson topic"],
            answer: "Practice with feedback",
            explanation: "Adaptive practice and feedback are used to stabilize the knowledge point.",
          },
        ],
      },
    ]),
);

const PHRASE_REPLACEMENTS = [
  ["乐理智学平台", "MusicAI Learning Platform"],
  ["乐理智学", "MusicAI"],
  ["音乐理论智能学习平台", "Music Theory Intelligent Learning Platform"],
  ["AI 驱动 · 自主学习", "AI-Assisted Adaptive Learning"],
  ["智能引导学习", "Adaptive guidance"],
  ["互动音乐工作台", "Interactive music workspace"],
  ["每个单元下直接展示课时卡片，点击课时即可进入课前预习、内容呈现、课堂练习与课后作业。", "Each unit displays lesson cards directly. Students can enter pre-lesson preparation, content delivery, classroom practice, and post-lesson homework from one page."],
  ["首页", "Home"],
  ["菜单", "Menu"],
  ["综合测评", "Assessment"],
  ["综合测评报告", "Assessment Report"],
  ["教师后台", "Teacher Dashboard"],
  ["教师后台加载中...", "Loading teacher dashboard..."],
  ["教师后台登录", "Teacher Dashboard Login"],
  ["请使用教师账号登录后再查看 BKT 概览、学生报告和试点数据。", "Sign in with the teacher account to view the BKT overview, student reports, and pilot data."],
  ["账号", "Username"],
  ["密码", "Password"],
  ["登录", "Log In"],
  ["退出登录", "Log Out"],
  ["测评", "Assessment"],
  ["贡献者：", "Contributor: "],
  ["综合得分", "Overall Score"],
  ["已完成", "Completed"],
  ["平均评分", "Average Rating"],
  ["等级", "Level"],
  ["优秀", "Excellent"],
  ["良好", "Good"],
  ["一般", "Fair"],
  ["需加强", "Needs Practice"],
  ["未开始", "Not started"],
  ["智能学习建议", "Learning Recommendation"],
  ["开始任意课时后，系统会根据你的表现生成个性化建议。", "Start any lesson and the system will generate personalized recommendations from your performance."],
  ["建议每天进行 15-20 分钟短时练习，重点巩固基础概念，并结合 AI 导师查漏补缺。", "Practice 15-20 minutes daily, reinforce fundamentals, and use the AI Tutor to close gaps."],
  ["基础掌握较好，建议重点突破薄弱章节，并在创作与实验模块中实践乐理知识。", "Your foundation is improving. Focus on weaker chapters and apply concepts in creative and lab tasks."],
  ["当前表现优秀，建议挑战综合题，并把所学知识迁移到创作与分析任务中。", "Performance is strong. Try integrated questions and transfer concepts into creation and analysis tasks."],
  ["学习进度", "Progress"],
  ["课前预习", "Pre-Lesson"],
  ["内容呈现", "Content"],
  ["课堂练习", "Classroom Practice"],
  ["课后作业", "Homework"],
  ["AI 导师", "AI Tutor"],
  ["AI 乐理导师", "AI Music Theory Tutor"],
  ["知识导图", "Knowledge Map"],
  ["中心主题", "Central Topic"],
  ["先看 4 个主节点建立整体框架，再进入课时内容查看完整 PPT。", "Review the four main nodes first, then open the full lesson PPT."],
  ["先看 4 个主节点建立框架，再进入课时内容和课堂练习。", "Review the four main nodes first, then move to content and practice."],
  ["点击进入对应课时内容", "Open the related content"],
  ["互动预习", "Interactive Preview"],
  ["预习建议", "Preview Plan"],
  ["看导图", "Review Map"],
  ["先抓住本课主线", "Identify the lesson structure"],
  ["进课时内容", "Open Content"],
  ["查看完整 PPT", "View the full PPT"],
  ["做课堂练习", "Practice"],
  ["检验薄弱点", "Check weak points"],
  ["进入课时内容", "Open Lesson Content"],
  ["直接去课堂练习", "Go to Practice"],
  ["知识点掌握摘要", "Knowledge Mastery Summary"],
  ["已掌握较好：", "Stronger points: "],
  ["当前薄弱点：", "Current weak points: "],
  ["下一步建议：", "Next recommendation: "],
  ["尚未形成稳定强项", "No stable strength yet"],
  ["暂无", "None"],
  ["得分", "Score"],
  ["练习说明", "Practice Notes"],
  ["系统会记录错误类型，供课后作业与教师后台汇总使用。", "The system records error types for homework and teacher-dashboard summaries."],
  ["课堂练习引导", "Practice Guidance"],
  ["互动检测", "Interactive Check"],
  ["课堂练习题", "Practice Question"],
  ["概念识别", "Concept Recognition"],
  ["知识点匹配", "Knowledge-Point Match"],
  ["排除辨析", "Exclusion"],
  ["应用题", "Application"],
  ["分析题", "Analysis"],
  ["事实记忆", "Specific Fact"],
  ["对比辨析", "Contrast"],
  ["综合题", "Integrated Question"],
  ["下一题", "Next Question"],
  ["切换到新的 20 题", "Generate a New 20-Question Set"],
  ["答对题数/总题数：", "Correct / Total: "],
  ["作业规范", "Homework Guidelines"],
  ["查看作业规范", "Show Homework Guidelines"],
  ["收起作业规范", "Hide Homework Guidelines"],
  ["联系说明", "Support Notes"],
  ["查看联系说明", "Show Support Notes"],
  ["收起联系说明", "Hide Support Notes"],
  ["音乐创作实验室", "Music Creation Lab"],
  ["让我们一起来创造音乐吧", "Create music with the interactive lab."],
  ["课时 PPT", "Lesson PPT"],
  ["上一页", "Previous"],
  ["下一页", "Next"],
  ["点击当前幻灯片可放大查看", "Click the current slide to enlarge it."],
  ["打开原始 PPT", "Open Original PPT"],
  ["互动音乐实验页面", "Interactive music lab page"],
  ["打开", "Open"],
  ["收起", "Collapse"],
  ["新窗口打开", "Open in New Window"],
  ["课程评价", "Course Evaluation"],
  ["回答正确：", "Correct: "],
  ["需要修正：", "Needs revision: "],
  ["知识点分布图", "Knowledge Distribution"],
  ["学习重点提示", "Learning Focus"],
  ["易错点", "Common Pitfalls"],
  ["做题抓手", "Practice Handles"],
  ["音高识别", "Pitch Identification"],
  ["找到这个音", "Find this note"],
  ["播放音程", "Play Interval"],
  ["播放和弦", "Play Chord"],
  ["高音谱号", "Treble Clef"],
  ["低音谱号", "Bass Clef"],
  ["播放节奏", "Play Rhythm"],
  ["提交答案", "Submit Answer"],
  ["正确", "Correct"],
  ["错误", "Incorrect"],
  ["正确答案是", "The correct answer is"],
  ["拍照上传", "Take Photo"],
  ["相册上传", "Upload Image"],
  ["移除", "Remove"],
  ["发送", "Send"],
  ["拍照", "Camera"],
  ["相册", "Gallery"],
  ["思考中...", "Thinking..."],
  ["请求失败，请稍后重试。", "Request failed. Please try again later."],
  ["AI 服务暂时不可用，请稍后重试。", "The AI service is temporarily unavailable. Please try again later."],
  ["服务是否在线", "Service Online"],
  ["概览接口是否成功", "Overview API"],
  ["BKT 接口是否成功", "BKT API"],
  ["正常", "OK"],
  ["失败", "Failed"],
  ["检测中", "Checking"],
  ["知识点口径", "Knowledge-Point Scope"],
  ["一键初始化教师样本数据", "Initialize Teacher Sample Data"],
  ["初始化中...", "Initializing..."],
  ["导出教师样本报告", "Export Teacher Sample Report"],
  ["预览样本报告", "Preview Sample Report"],
  ["导出 JSON", "Export JSON"],
  ["导出 CSV", "Export CSV"],
  ["导出 HTML", "Export HTML"],
  ["数据记录数", "Records"],
  ["学生数", "Students"],
  ["平均得分", "Average Score"],
  ["已提交作业", "Homework Submitted"],
  ["学生学习概览", "Student Learning Overview"],
  ["课时数据概览", "Lesson Data Overview"],
  ["最近学习记录", "Recent Learning Records"],
  ["访问课时", "Lessons visited"],
  ["学习时长", "Study time"],
  ["错误数", "Errors"],
  ["作业提交", "Homework"],
  ["参与学生", "Active students"],
  ["累计错误", "Total errors"],
  ["已提交", "Submitted"],
  ["未提交", "Not submitted"],
  ["无", "None"],
  ["是", "Yes"],
  ["否", "No"],
];

const TEXT_REPLACEMENTS = PHRASE_REPLACEMENTS.sort((a, b) => b[0].length - a[0].length);

export function translateDemoText(value) {
  if (!ENGLISH_DEMO_ENABLED || typeof value !== "string" || !value) return value;
  let text = value;
  for (const [source, target] of TEXT_REPLACEMENTS) {
    if (text.includes(source)) text = text.split(source).join(target);
  }
  text = text
    .replace(/第\s*(\d+)\s*\/\s*(\d+)\s*题/g, "Question $1 / $2")
    .replace(/第\s*(\d+)\s*单元/g, "Chapter $1")
    .replace(/第\s*0?(\d+)\s*课时/g, "Lesson $1")
    .replace(/第\s*0?(\d+)\s*课/g, "Lesson $1")
    .replace(/第\s*(\d+)\s*小节/g, "Measure $1")
    .replace(/(\d+)\s*个预习主线/g, "$1 preview strands")
    .replace(/(\d+)\s*分钟/g, "$1 min")
    .replace(/已完成\s*(\d+)%/g, "Completed $1%")
    .replace(/当前剩余时间/g, "Time remaining")
    .replace(/约\s*(\d+)\s*min/g, "about $1 min")
    .replace(/：/g, ": ")
    .replace(/，/g, ", ")
    .replace(/。/g, ".")
    .replace(/；/g, "; ");
  return text;
}

function translateElementAttributes(root) {
  const elements = root.querySelectorAll?.("[placeholder], [alt], [title], [aria-label]") || [];
  elements.forEach((element) => {
    ["placeholder", "alt", "title", "aria-label"].forEach((name) => {
      const current = element.getAttribute(name);
      if (!current) return;
      const next = translateDemoText(current);
      if (next !== current) element.setAttribute(name, next);
    });
  });
}

function translateTextNodes(root) {
  if (!root || typeof document === "undefined") return;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach((node) => {
    const current = node.nodeValue;
    const next = translateDemoText(current);
    if (next !== current) node.nodeValue = next;
  });
  translateElementAttributes(root);
}

export function installEnglishDemoShell() {
  if (!ENGLISH_DEMO_ENABLED || typeof window === "undefined" || typeof document === "undefined") return;
  document.documentElement.lang = "en";
  document.title = "MusicAI Learning Platform";

  let scheduled = false;
  const run = () => {
    scheduled = false;
    translateTextNodes(document.body);
  };
  const schedule = () => {
    if (scheduled) return;
    scheduled = true;
    window.requestAnimationFrame(run);
  };

  schedule();
  const observer = new MutationObserver(schedule);
  observer.observe(document.body, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ["placeholder", "alt", "title", "aria-label"] });
}
